CC = g++
CFLAGS = -fPIC -shared
SRC = MET_class.cpp
OUT = libMET_class.so

# Here I specified the variables for clarity, for myself

Makefile: MET_class.cpp
	g++ -fPIC -shared MET_class.cpp -o libMET_class.so

